server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  data:
    redis:
      host: localhost
      port: 1201
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: true
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: localhost:9200
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://127.0.0.1:3307/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 121221
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    redis:
      cache-null-values: false


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds
app:
  services:
    profile: http://localhost:8082/profile

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
  show-actuator: true
  packages-to-scan: com.ndt.identity_service


