version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.2'
    hostname: zoo1
    container_name: zoo1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - C:\Users\taira\Desktop\java\docker_repository\zoo\data:/bitnami/zoo

  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_OFFSETS_RETENTION_MINUTES: 60
    volumes:
      - C:\Users\taira\Desktop\java\docker_repository\kafka\data:/bitnami/kafka