server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8081
          predicates:
          - Path=${app.api-prefix}/identity/**
          filters:
          - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8082
          predicates:
          - Path=${app.api-prefix}/profile/users/**
          filters:
          - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: openai
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**,/swagger-ui/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs


springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /identity/v3/api-docs
        name: Identity Service
      - url: /profile/v3/api-docs
        name: Profile Service
      - url: /notification/v3/api-docs
        name: Notification Service
    enabled: true
    path: /swagger-ui
  show-actuator: true
  packages-to-scan: com.ndt.gateway