server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  data:
    redis:
      host: localhost
      port: 1201
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: true
      elasticsearch:
        repositories:
          enabled: false
    elasticsearch:
      cluster-node: localhost:9200
      cluster-names: docker-cluster
      repositories:
        enabled: true
      auto-index-creation: true

  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds
