version: '3.2'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j/data:/data
    environment:
      NEO4J_AUTH: neo4j/121221TTh40

