version: '3.1'

services:

  mongodb:
    image: bitnami/mongodb:7.0.12
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      #    - ./mongoDb/data:/data #defaul
      - C:\Users\taira\Desktop\java\docker_repository\notification-service\data:/bitnami/mongodb